### PR TITLE
gamezone release 0.1.0

### PR DESCRIPTION
**Pull request by SamTush**
## What does this PR do?

This PR is raised to implement the following features: 👍 :

- [x] When the page loads, the webapp shows the list of games from the API. 
- [x] Display the image of the game and it's name.
- [x] The application navigates to the details page when the user clicks a game.
- [x] In the details page, the webapp retrieves data from the API to show detailed data about the game.
- [x] When the user clicks on the "Back" button (<), the user navigates to the home page.

## Description of the task to be completed ↓↓ 

- Fetch data from API and displays it in main section and details section

  
## How should it be tested

Clone the repository
```
git clone https://github.com/SamTush/gamezone.git
```
Navigate to the folder
```
cd gamezone
```
Checkout the branch
```
git checkout develop
```

## How should it be run

Run website in browser.
```
  npm start
```

## How to run test

```
  npm test
```

#### Thanks for reviewing my PR 😊

### CODE REVIEW

**Review by alexander16108 — CHANGES_REQUESTED** [review]
Hi @SamTush , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights

- [ ] Responsive design ✅
- [ ] Featured speakers added dynamically ✅

## Required Changes ♻️
_Check the comments under the review._

- [ ] your README should contain an "Acknowledgements" section or similar that gives appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/).
- [ ] You should record a video presenting the features of the project.
- [ ] The maximum length of the video should be 5 minutes.
- [ ] The video should contain a clear and objective description of the project in professional English. The topic and purpose of the project are made clear.
- [ ] The video should contain a project demo, highlighting all the project features.
- [ ] The video should highlight a piece of the code the student finds interesting or is proud of making.
- [ ] please add your images into a folder to make your file look more professional, presentable and easy to access
- [ ] You should create unit test for different components of the app and some pure functions in Redux code
- [ ] you should have integration tests using React Testing Library
- you can perform a mocking data fetching and Redux Store connection

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] I would recommend you use high resolution images for your desktop version because it seem the current one is overly stretched out and look unappealing 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Tufahel — CHANGES_REQUESTED** [review]
# Status: Required Changes :recycle:
Hi @SamTush :wave: 

Well done on implementing some of the required changes!!! 👍 
You still need to fix some issues before moving to the next project. :running_man: 

## Highlights 🌟

Alt Text

✔️ Linters checks are passing.
✔️ You have used the correct git-flow.
✔️ Readme is professional.
✔️ Commit messages are professional.

## Required Changes ♻️

- [ ] A professional presentation can help us to attract the interviewer or the project reviewer in our future jobs. In order to create a professional presentation we need to take care of the following things:
  - The maximum length of the video is 5 minutes.
  - The video contains a clear and objective description of the project in professional English. 
  - The topic and purpose of the project are made clear.
  - The video contains a demo of the project, highlighting all the project features.
  - The video contains a highlight about a piece of the code the student finds interesting or is proud of making.

> Currently in the video you have covered almost everything but missed the last one: `highlight a piece of the code the student finds interesting or is proud of making`.

`Kindly record the video again from the beginning and  highlight a piece of the code you found interesting or are proud of making.`

## Optional suggestions 🤷‍♂️

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.
- You can mail me at [Mail](mailto:tufahel96@gmail.com) or ask any question at Slack, `Name: Tufahel`

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by emmiiorji — APPROVED** [review]
Hi @SamTush, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<div align='center'>

</div>

## Good Highlights✔️
- Everything looks good
- Good documentation in readme

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by SamTush** [comment]
Thank you @emmiiorji @Tufahel @alexander16108 for reviewing my PR

**Pull request merged**
